spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
    client:
      client-id: acme
  enable-csrf: false
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://${mysql_host:192.168.1.63}:3306/spring_cloud_event?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tenxcloud
    platform: mysql
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://${user_service.host:localhost}:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://${online_store_web.host:localhost}:8787
  enable-csrf: false
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:8761/eureka/
---
spring:
  profiles: docker
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      client-id: acme
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  application:
    name: account-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
